services:
  auth_service:
    build: ./backend/auth_service
    ports:
      - 8001:80
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=travel_planner
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
      
  travel_service:
    build: ./backend/travel_service
    ports:
      - "8000:8000"
    env_file:
      - .env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: travel_planner
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
