services:
  frontend:
    build: 
      context: ./frontend
      args:
        CONFIGURATION: development
    ports:
      - 4200:80
    depends_on:
      - travel_service
      - auth_service

  auth_service:
    build: ./backend/auth_service
    ports:
      - 8001:80
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=travel_planner
      - DB_HOST=postgres
    depends_on:
      - postgres
      
  travel_service:
    build: ./backend/travel_service
    ports:
      - 8000:80
    environment:
      - MONGODB_URI=mongodb://mongo_db:27017/travel_planner
      - MONGODB_DB=travel_planner
      - AUTH_SERVICE_INTERNAL_URL=http://auth_service:80/
      - AUTH_SERVICE_EXTERNAL_URL=http://localhost:8001/
    env_file:
      - .env
    depends_on:
      - mongo_db
      
  monitoring_service:
    build: ./backend/monitoring_service
    ports:
      - 8080:80
    environment:
      - MONGODB_URI=mongodb://mongo_db:27017/travel_planner
      - MONGODB_DB=travel_planner
    depends_on:
      - mongo_db
      
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: travel_planner
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo_db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local
