apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: ghcr.io/robbiesumner/travel-planner-auth_service:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "travel_planner"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
