# GitHub Actions workflow to build and push Docker images for all services
# This workflow builds images for auth_service, travel_service, monitoring_service, and frontend
# and pushes them to GitHub Container Registry (ghcr.io)

name: Build and Push Docker Images

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_PREFIX: ${{ github.repository_owner }}/travel-planner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push auth_service image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/auth_service
          file: ./backend/auth_service/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-auth_service:latest

      - name: Build and push travel_service image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/travel_service
          file: ./backend/travel_service/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-travel_service:latest

      - name: Build and push monitoring_service image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/monitoring_service
          file: ./backend/monitoring_service/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-monitoring_service:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-frontend:latest
